info:
  app:
    name: LibriMem User
    description: Manage the users of LM
    version: 1.0.0
  company:
    name: Erinbro

server:
  port: 8082
  error:
    include-message: always
    include-binding-error: always
    include-stacktrace: always

spring:
  application:
    name: user
  datasource:
    username: erinbro
    url: jdbc:postgresql://localhost:5432/librimem
    password: erinbro
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 16225959959-31ct8du4slpf0phr3a5nfsf2k854llbc.apps.googleusercontent.com
            clientSecret: 16225959959-31ct8du4slpf0phr3a5nfsf2k854llbc.apps.googleusercontent.com
            scope:
              - email
              - profile
