server:
  port: 8082

spring:
  application:
    name: User
  datasource:
    username: erinbro
    url: jdbc:postgresql://librimem_db:5432/users
    password: erinbro
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true