import { IArticle } from "./article.interface"
import { IAuthor } from "./author.interface"
import { IBook } from "./book.interface"
import { IChapter } from "./chapter.interace"
import { ICollection } from "./collection.interface"
import { ICitation } from "./citation.interface"
import { IComment } from "./comment.interface"
import { ICommentary } from "./commentary.interface"
import { IEntity } from "./entity.interface"
import { IEvent } from "./event.inerface"
import { IFlashcard } from "./flashcard.interface"
import { IGenre } from "./genre.interface"
import { INote } from "./note.interface"
import { IOpinion } from "./opinion.interface"
import { IParagraph } from "./paragraph.interface"
import { IQuestion } from "./question.interface"
import { ISentence } from "./sentence.interface"
import { ISubject } from "./subject.interface"
import { ISummary } from "./summary.interface"
import { ITeaching } from "./teaching.interface"
import { IWord } from "./word.interface"

export { IArticle, IAuthor, IBook, IChapter, ICitation, IComment, ICommentary, IEntity, IEvent, IFlashcard, IGenre, INote, IOpinion, IParagraph, IQuestion, ISentence, ISubject, ISummary, ITeaching, IWord, ICollection };
