version: "3.7"

services:
  librimem_db:
    container_name: librimem_db
    image: postgres:13
    environment:
      POSTGRES_USER: erinbro
      POSTGRES_PASSWORD: erinbro
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_pdf:
