info:
  app:
    name: Book
    description: Manage your lecture
    version: 1.0.0
  company:
    name: Erinbro

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: prometheus

server:
  port: 8080
  error:
    include-message: always
    include-binding-error: always
    include-stacktrace: always

spring:
  application:
    name: book
  datasource:
    username: erinbro
    url: jdbc:postgresql://localhost:5432/librimem
    password: erinbro
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

clients:
  chapter:
    url: http://localhost:8081/api/v1/book