version: "3.7"

services:
  librimem_db:
    container_name: librimem_db
    image: postgres:13
    networks:
      - postgres_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: erinbro
      POSTGRES_PASSWORD: erinbro
      PGDATA: /data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: erinbro
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network

  # librimem-frontend
  librimem_client:
    container_name: librimem_client
    image: josemagne/librimem-frontend:latest
    networks:
      - librimem_network

  librimem_book:
    container_name: librimem_book
    image: josemagne/book:latest
    networks:
      - librimem_network
    ports:
      - "8080:8080"

  librimem_chapter:
    container_name: librimem_chapter
    image: josemagne/chapter:latest
    networks:
      - librimem_network

  librimem_user:
    container_name: librimem_user
    image: josemagne/user:latest


volumes:
  postgres:
  pgadmin:

networks:
  librimem_network:
    driver: bridge
  postgres_network:
    driver: bridge